resources:
  - name: jfrogtw_hw_repo
    type: GitRepo
    configuration:
      gitProvider: twgithub
      path: jfrogtw/jfrog-pipelines-hw
      branches:
        include: master
        
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: jfrogtw_hw_repo
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name
            - echo $res_jfrogtw_hw_repo_resourcePath
            - echo $res_jfrogtw_hw_repo_gitProvider_name
            - echo $res_jfrogtw_hw_repo_commitSha
            - sleep 5s
            - echo $MY_MESSAGE

      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name
            - echo $MY_MESSAGE

      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name
            - echo $MY_MESSAGE

      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
            - name: step_3
        execution:
          onExecute:
            - echo "Running " $pipeline_name "|" $step_name
            - echo $MY_MESSAGE
